version: '3.8'

services:
  client:
    image: dwiputrasam/client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    image: dwiputrasam/server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    depends_on:
      - database

  database:
    image: dwiputrasam/database
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dwisam001
      POSTGRES_DB: postgres
    volumes:
      - ./database/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql