version: '3.8'

services:
  client:
    image: dwiputrasam/client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    image: dwiputrasam/api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    depends_on:
      - database